document.writeln("			<div class=\'footer\'>");
document.writeln("				<div class=\'footer-inner\'>");
document.writeln("					<div class=\'footer-content\'>");
document.writeln("						<span class=\'bigger-120\'>");
document.writeln("							<span class=\'blue bolder\'>奔跑贷</span>");
document.writeln("							&copy; 2017");
document.writeln("						</span>");
document.writeln("");
document.writeln("						&nbsp; &nbsp;");
document.writeln("						<span class=\'action-buttons\'>");
document.writeln("							<a target=\'_blank\' href=\'http://wpa.qq.com/msgrd?v=3&uin=QQhaoma&site=qq&menu=yes\'>");
document.writeln("								<i class=\'ace-icon fa fa-qq light-blue bigger-150\'></i>");
document.writeln("							</a>");
document.writeln("");
document.writeln("							<a href=\'#\'>");
document.writeln("								<i class=\'ace-icon fa fa-weixin text-primary bigger-150\'></i>");
document.writeln("							</a>");
document.writeln("");
document.writeln("							<a href=\'#\'>");
document.writeln("								<i class=\'ace-icon fa fa-weibo orange bigger-150\'></i>");
document.writeln("							</a>");
document.writeln("						</span>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</div>");