document.writeln("");
document.writeln("					<div id=\'navbar\' class=\'navbar navbar-default  navbar-fixed-top   navbar-top-stay      ace-save-state\'>");
document.writeln("						<div class=\'navbar-container ace-save-state\' id=\'navbar-container\'>");
document.writeln("							<button type=\'button\' class=\'navbar-toggle menu-toggler pull-left\' id=\'menu-toggler\' data-target=\'#sidebar\'>");
document.writeln("								<span class=\'sr-only\'>Toggle sidebar</span>");
document.writeln("");
document.writeln("								<span class=\'icon-bar\'></span>");
document.writeln("");
document.writeln("								<span class=\'icon-bar\'></span>");
document.writeln("");
document.writeln("								<span class=\'icon-bar\'></span>");
document.writeln("							</button>");
document.writeln("");
document.writeln("								<a href=\'index.html\' class=\'navbar-brand\'>");
document.writeln("									<small>");
document.writeln("										<i class=\'fa fa-leaf\'></i>");
document.writeln("										奔跑贷");
document.writeln("									</small>");
document.writeln("								</a>");
document.writeln("");
document.writeln("							<div class=\'navbar-buttons navbar-header pull-right\' role=\'navigation\'>");
document.writeln("								<ul class=\'nav ace-nav\'>");
document.writeln("");
document.writeln("									<li class=\'light-blue dropdown-modal\'>");
document.writeln("										<a data-toggle=\'dropdown\' href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("											<img class=\'nav-user-photo\' src=\'../assets/images/avatars/user.jpg\' alt=\'Jason\'s Photo\' />");
document.writeln("											<i class=\'ace-icon fa fa-caret-down\'></i>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<ul class=\'user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close\'>");
document.writeln("											<li>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'ace-icon fa fa-cog\'></i>");
document.writeln("													设置");
document.writeln("												</a>");
document.writeln("											</li>");
document.writeln("");
document.writeln("											<li>");
document.writeln("												<a href=\'profile.html\'>");
document.writeln("													<i class=\'ace-icon fa fa-user\'></i>");
document.writeln("													个人中心");
document.writeln("												</a>");
document.writeln("											</li>");
document.writeln("");
document.writeln("											<li class=\'divider\'></li>");
document.writeln("");
document.writeln("											<li>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'ace-icon fa fa-power-off\'></i>");
document.writeln("													退出");
document.writeln("												</a>");
document.writeln("											</li>");
document.writeln("										</ul>");
document.writeln("									</li>");
document.writeln("");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("						</div><!-- /.navbar-container -->");
document.writeln("					</div>");