document.writeln("");
document.writeln("			<div id=\'sidebar\' class=\'sidebar                  responsive                    ace-save-state\'>");
document.writeln("				<script type=\'text/javascript\'>");
document.writeln("					try{ace.settings.loadState(\'sidebar\')}catch(e){}");
document.writeln("				</script>");
document.writeln("");
document.writeln("				<div class=\'sidebar-shortcuts\' id=\'sidebar-shortcuts\'>");
document.writeln("");
document.writeln("                <img width=\'150\' height=\'150\' alt=\'150x150\' src=\'assets/images/logo/logo.png\'>");
document.writeln("");
document.writeln("				</div><!-- /.sidebar-shortcuts -->");
document.writeln("");
document.writeln("				<ul class=\'nav nav-list\'>");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'index.html\'>");
document.writeln("							<i class=\'menu-icon ace-icon glyphicon glyphicon-home\'></i>");
document.writeln("							<span class=\'menu-text\'> 首页 </span>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("							<i class=\'menu-icon fa fa-list\'></i>");
document.writeln("							<span class=\'menu-text\'> 流量大厅 </span>");
document.writeln("");
document.writeln("							<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'tables.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									最新流量");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'jqgrid.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									我的流量");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'jqgrid.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									淘单大厅");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("							<i class=\'menu-icon ace-icon glyphicon glyphicon-user\'></i>");
document.writeln("							<span class=\'menu-text\'> 个人中心 </span>");
document.writeln("");
document.writeln("							<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'profile.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									基本资料");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'inbox.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									流量充值");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("					");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("							<i class=\'menu-icon ace-icon glyphicon glyphicon-print\'></i>");
document.writeln("							<span class=\'menu-text\'> 详单查询 </span>");
document.writeln("");
document.writeln("							<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'profile.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									详单查询");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'inbox.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									查询列表");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("");
document.writeln("					<li class=\'\'>");
document.writeln("						<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("							<i class=\'menu-icon fa fa-desktop\'></i>");
document.writeln("							<span class=\'menu-text\'>");
document.writeln("								后台管理");
document.writeln("							</span>");
document.writeln("");
document.writeln("							<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("						</a>");
document.writeln("");
document.writeln("						<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("						<ul class=\'submenu\'>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'typography.html\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("									后台仪表盘");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("									商户管理");
document.writeln("									<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("								<ul class=\'submenu\'>");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'top-menu.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											新增商户");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li>");
document.writeln("");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'two-menu-1.html\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("											商户列表");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li>");
document.writeln("");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("									流量");
document.writeln("									<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("								<ul class=\'submenu\'>");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'#\'>");
document.writeln("											<i class=\'menu-icon fa fa-leaf green\'></i>");
document.writeln("											流量统计图表页面");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("									</li>");
document.writeln("");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("											<i class=\'menu-icon fa fa-eye orange\'></i>");
document.writeln("");
document.writeln("											流量列表");
document.writeln("											<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("										<ul class=\'submenu\'>");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right purple\'></i>");
document.writeln("													总流量列表");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa-caret-right fa pink\'></i>");
document.writeln("													常价流量");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right green\'></i>");
document.writeln("													淘单流量");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("										</ul>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("");
document.writeln("							<li class=\'\'>");
document.writeln("								<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("									<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("									账户管理");
document.writeln("									<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("								</a>");
document.writeln("");
document.writeln("								<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("								<ul class=\'submenu\'>");
document.writeln("");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("											管理员");
document.writeln("											<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("										<ul class=\'submenu\'>");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("													基本资料");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("													修改密码");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("										</ul>");
document.writeln("									</li>");
document.writeln("");
document.writeln("									<li class=\'\'>");
document.writeln("										<a href=\'#\' class=\'dropdown-toggle\'>");
document.writeln("											<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("");
document.writeln("											子账号");
document.writeln("											<b class=\'arrow fa fa-angle-down\'></b>");
document.writeln("										</a>");
document.writeln("");
document.writeln("										<b class=\'arrow\'></b>");
document.writeln("");
document.writeln("										<ul class=\'submenu\'>");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("													子账号列表");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("");
document.writeln("											<li class=\'\'>");
document.writeln("												<a href=\'#\'>");
document.writeln("													<i class=\'menu-icon fa fa-caret-right\'></i>");
document.writeln("													新增子账号");
document.writeln("												</a>");
document.writeln("");
document.writeln("												<b class=\'arrow\'></b>");
document.writeln("											</li>");
document.writeln("										</ul>");
document.writeln("									</li>");
document.writeln("									");
document.writeln("");
document.writeln("								</ul>");
document.writeln("							</li>");
document.writeln("						</ul>");
document.writeln("					</li>");
document.writeln("");
document.writeln("				</ul><!-- /.nav-list -->");
document.writeln("");
document.writeln("");
document.writeln("			</div>");